### PR TITLE
Feature/column

### PR DESCRIPTION
**Pull request by TynchtykbekAkmatov**

### CODE REVIEW

**Review by ChyngyzIshen — COMMENTED** [review]
Line or Column?

**Comment by ChyngyzIshen** [comment]
Resolve conflicts please

**Comment by TynchtykbekAkmatov** [comment]
> 

Line

**Comment by TynchtykbekAkmatov** [comment]
> Строка или столбец?

Line

**Comment by TynchtykbekAkmatov** [comment]
> Line or Column?

Line

**Comment by TynchtykbekAkmatov** [comment]
> Resolve conflicts please

Ok

**Comment by ChyngyzIshen** [comment]
Good job!

**Pull request merged**
